### ISSUE TITLE
What is the UsersRepository?

### ISSUE THREAD

**Issue by bkayser** [saxond/bill#6]
https://github.com/saxond/bill/blob/2b9a7baf27d52ac1c30cf7279ced75e15242d7ad/server/src/main/java/com/bill/server/users/UsersController.java#L16

It looks like something that stores users, maybe tied to the DB, but it is never read in the UsersController and there are no annotations associated with the field.  Is this scaffolding?

**Comment by saxond** [comment]
That was used, but then the code moved to `AuthenticationInterceptor`.  I cleaned that up.
